version: '3.8'

services:
  db:
    image: postgres:13
    container_name: stockmaster_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stockmaster_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - stockmaster-net

  backend:
    build: ./backend
    container_name: stockmaster_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: stockmaster_db
      DB_USER: usuario
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - stockmaster-net

  frontend:
    build: ./frontend
    container_name: stockmaster_frontend
    ports:
      - "3000:3000"
    networks:
      - stockmaster-net

volumes:
  postgres_data:

networks:
  stockmaster-net:
    driver: bridge