version: '3.8'

services:
  # 1. Base de Datos
  db:
    image: postgres:13
    container_name: stockmaster_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stockmaster_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stockmaster-net

  # 2. Backend 
  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_NAME: stockmaster_db
      DB_USER: usuario
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - stockmaster-net

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: stockmaster_frontend
    expose:
      - "3000"
    networks:
      - stockmaster-net

  # 4. Nginx
  nginx:
    build: ./nginx
    container_name: stockmaster_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - stockmaster-net
  # 5. Servicio de Backups
  backup:
    build: ./backup
    container_name: stockmaster_backup
    environment:
      DB_HOST: db
      DB_NAME: stockmaster_db
      DB_USER: usuario
      DB_PASSWORD: password
    depends_on:
      - db
   
    volumes:
      - ./respaldos:/backups
    networks:
      - stockmaster-net

volumes:
  postgres_data:

networks:
  stockmaster-net:
    driver: bridge